// CREAR EL COMPONENTE DE HOME Y ESTILARLO

// CREAR EL COMPONENTE DE PREGUNTAS Y ESTILARLO
// ESTILAR LAS PREGUNTAS COMO RADIO BUTTONS (VER EN GOOGLE COMO ESTILAR EL RADIO COMO UN BUTTON)

// HACER QUE CUANDO SE PULSE EL BOTÓN EN HOME CON UN STATE APAREZCA EL COMPONENTE DE PREGUNTAS

import Home from "/src/Components/Home";

export default function App() {
	return (
		<div>
			<Home />
		</div>
	);
}
